name: 🚨 Remove Channel
description: Request to remove a channel
title: "Remove: "
labels: [ "DMCA" ]

body:
  - type: markdown
    attributes:
      value: |
       Please fill out the issue template as much as you can so we could efficiently process your request

  - type: input
    id: name
    attributes:
      label: Channel Names
      description: Full name of every channel to be removed
      placeholder: 'Fox Life Russia'
    validations:
      required: true
     
  - type: input
    id: link
    attributes:
      label:  DMCA Notice
      description: A link to your published complaint form that must be filled here https://github.com/contact/dmca
      placeholder: 'https://github.com/github/dmca/blob/3ce1c9402c6b7e46dcbbea6ff866d6a44e75c72a/2021/03/2021-03-26-sky-italia.md'
    validations:
      required: true
         
  - type: input
    id: notes
    attributes:
      label: Notes
      placeholder: 'Anything else we should know?'
