name: cleanup
on:
  workflow_dispatch:
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=branch_name::$(date +'bot/cleanup-%s')"
        id: create-branch-name
      - run: |
          git config user.name 'iptv-bot[bot]'
          git config user.email '84861620+iptv-bot[bot]@users.noreply.github.com'
      - run: git checkout -b ${{ steps.create-branch-name.outputs.branch_name }}
      - run: npm install
      - run: node scripts/commands/create-database.js
      - run: node scripts/commands/cleanup-database.js
      - run: node scripts/commands/update-playlists.js
      - run: |
          git add channels/*
          git commit -m "[Bot] Update playlists"
      - uses: tibdex/github-app-token@v1
        if: ${{ !env.ACT }}
        id: create-app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: repo-sync/pull-request@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        id: pull-request
        with:
          github_token: ${{ steps.create-app-token.outputs.token }}
          source_branch: ${{ steps.create-branch-name.outputs.branch_name }}
          destination_branch: 'master'
          pr_title: '[Bot] Remove broken links'
          pr_body: |
            This pull request is created by [cleanup][1] workflow.

            [1]: https://github.com/iptv-org/iptv/actions/runs/${{ github.run_id }}
